import type { Metadata } from "next";
import {Noto_Sans_Bengali } from "next/font/google";
import "./globals.css";

const banglaFonts = Noto_Sans_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${banglaFonts.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        navbar
        <main>
        {children}
        </main>
        footer
        </body>
    </html>
  );
}
