import type { Metadata } from "next";
import { Anek_Bangla } from "next/font/google";
import "./globals.css";
import HeaderPage from "@/components/header";
import Navlinks from "@/components/navlinks";
import Footer from "@/components/Footer";

const banglaFonts = Anek_Bangla({
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${banglaFonts.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F0F5F0]">
        <HeaderPage />
        <Navlinks />
        
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
